AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mailing-list

  Sample SAM Template for mailing-list

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'POST'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  CreateGroupFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: create_group/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: prod-mailing-list-creategroup
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref GroupSubscribersTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GroupSubscribersTable      
      Events:
        MailingList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /groups
            Method: post
  JoinGroupFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: join_group/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: prod-mailing-list-joingroup
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref GroupSubscribersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupSubscribersTable
      Events:
        MailingList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /groups/{group-id}
            Method: post
  SendPostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: send_post/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: prod-mailing-list-send-post
      Architectures:
        - x86_64
      Environment:
        Variables:
          MESSAGES_BUCKET: !Ref Messages
          TABLE_NAME: !Ref GroupSubscribersTable
      Policies:
         - S3WritePolicy:
              BucketName: !Ref Messages
         - DynamoDBReadPolicy:
             TableName: !Ref GroupSubscribersTable
      Events:
        MailingList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /groups/{group-id}/post
            Method: post
  ViewGroupsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: view_groups/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: prod-mailing-list-viewgroups
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref GroupSubscribersTable
      Policies:
         - DynamoDBReadPolicy:
             TableName: !Ref GroupSubscribersTable
      Events:
        MailingList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /groups
            Method: get
  
  GroupSubscribersTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: groups-db      
      AttributeDefinitions: 
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema: 
        - AttributeName: PK
          KeyType: HASH 
        - AttributeName: SK
          KeyType: RANGE 
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SendEmailFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: send_email/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref Messages
        - DynamoDBReadPolicy:
            TableName: !Ref GroupSubscribersTable
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      Environment:
        Variables:
          TABLE_NAME: !Ref GroupSubscribersTable
          VERIFIED_EMAIL: pintolearning@gmail.com
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SendMessagesQueue.Arn
            BatchSize: 5
  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt SendMessagesQueue.Arn
      Queues:
        - !Ref SendMessagesQueue
  Messages:
    Type: AWS::S3::Bucket    
    Properties:
      NotificationConfiguration:
        QueueConfigurations:
          - Event: 's3:ObjectCreated:*'
            Queue: !GetAtt SendMessagesQueue.Arn
  SendMessagesQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 360
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DLQ.Arn
        maxReceiveCount: 5
  DLQ:
    Type: AWS::SQS::Queue
  WebsiteS3Bucket:
    Type: AWS::S3::Bucket
    
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteS3Bucket.DomainName
            Id: mailing-list-hosting
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: "true"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: mailing-list-hosting
          ForwardedValues:
            QueryString: "false"
          ViewerProtocolPolicy: redirect-to-https
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub 'arn:aws:s3:::${WebsiteS3Bucket}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
    
    
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: mailing-list-OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
Outputs:
  CreateGroupApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateGroup function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/groups/"
  JoinGroupApi:
    Description: "API Gateway endpoint URL for Prod stage for JoinGroupFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/groups/"
  ViewGroupsApi:
    Description: "API Gateway endpoint URL for Prod stage for ViewGroupsFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/groups/"
  CloudFrontDist:
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebsiteBucket:
    Value: !Ref WebsiteS3Bucket
